/*
 * report.c — funnel outputs: JSON, a self-contained HTML dashboard, and a
 * taguchi .tgu for the surviving factors. No external resources are referenced.
 */

#include "robust.h"

#include <stdio.h>
#include <math.h>

int robust_write_json(const robust_result_t *r, const char *path, char *err) {
    FILE *f = fopen(path, "w");
    if (!f) { snprintf(err, DOE_ERR_SIZE, "cannot write '%s'", path); return -1; }

    fprintf(f, "{\n  \"keep_fraction\": %g,\n  \"n_factors\": %zu,\n  \"n_survivors\": %zu,\n",
            r->keep_fraction, r->k, r->n_survivors);

    fprintf(f, "  \"morris\": [\n");
    for (size_t i = 0; i < r->k; i++) {
        char *nm = doe_json_escape(r->effects[i].name);
        fprintf(f, "    {\"factor\": \"%s\", \"mu_star\": %g, \"sigma\": %g, \"mu\": %g, \"keep\": %s}%s\n",
                nm ? nm : "", r->effects[i].mu_star, r->effects[i].sigma, r->effects[i].mu,
                r->keep[i] ? "true" : "false", (i + 1 < r->k) ? "," : "");
        doe_free(nm);
    }
    fprintf(f, "  ],\n  \"sobol\": [\n");
    for (size_t i = 0; i < r->n_indices; i++) {
        const sobol_index_t *x = &r->indices[i];
        char *nm = doe_json_escape(x->name);
        fprintf(f, "    {\"factor\": \"%s\", \"S1\": %g, \"S1_lo\": %g, \"S1_hi\": %g, "
                   "\"ST\": %g, \"ST_lo\": %g, \"ST_hi\": %g}%s\n",
                nm ? nm : "", x->s1, x->s1_lo, x->s1_hi, x->st, x->st_lo, x->st_hi,
                (i + 1 < r->n_indices) ? "," : "");
        doe_free(nm);
    }
    fprintf(f, "  ]\n}\n");

    fclose(f);
    return 0;
}

int robust_write_html(const robust_result_t *r, const char *path, char *err) {
    FILE *f = fopen(path, "w");
    if (!f) { snprintf(err, DOE_ERR_SIZE, "cannot write '%s'", path); return -1; }

    fprintf(f,
        "<!DOCTYPE html>\n<html><head><meta charset=\"utf-8\">\n"
        "<title>Robust funnel report</title>\n<style>\n"
        "body{background:#0d1117;color:#c9d1d9;font-family:monospace;max-width:900px;margin:2em auto;padding:0 1em}\n"
        "h1,h2{color:#58a6ff} table{border-collapse:collapse;width:100%%;margin:1em 0}\n"
        "th,td{border:1px solid #30363d;padding:4px 8px;text-align:right} th{background:#161b22}\n"
        ".l{text-align:left} .keep{color:#3fb950;font-weight:bold} .drop{color:#8b949e}\n"
        "rect{fill:#58a6ff}\n</style></head><body>\n");

    fprintf(f, "<h1>Robust funnel</h1>\n<p>%zu factors &rarr; %zu survivors "
               "(keep_fraction = %g)</p>\n", r->k, r->n_survivors, r->keep_fraction);

    double maxmu = 0.0;
    for (size_t i = 0; i < r->k; i++) {
        if (r->effects[i].mu_star > maxmu) maxmu = r->effects[i].mu_star;
    }

    fprintf(f, "<h2>Morris screening</h2>\n<table>\n<tr>"
               "<th class=\"l\">factor</th><th>&mu;*</th><th>&sigma;</th>"
               "<th class=\"l\">status</th><th class=\"l\">&mu;* (relative)</th></tr>\n");
    for (size_t i = 0; i < r->k; i++) {
        double frac = (maxmu > 0.0) ? r->effects[i].mu_star / maxmu : 0.0;
        int w = (int)(frac * 200.0 + 0.5);
        char *nm = doe_html_escape(r->effects[i].name);
        fprintf(f, "<tr><td class=\"l\">%s</td><td>%.4g</td><td>%.4g</td>"
                   "<td class=\"l %s\">%s</td>"
                   "<td class=\"l\"><svg width=\"200\" height=\"12\"><rect width=\"%d\" height=\"12\"/></svg></td></tr>\n",
                nm ? nm : "", r->effects[i].mu_star, r->effects[i].sigma,
                r->keep[i] ? "keep" : "drop", r->keep[i] ? "KEEP" : "drop", w);
        doe_free(nm);
    }
    fprintf(f, "</table>\n");

    fprintf(f, "<h2>Sobol attribution (survivors)</h2>\n<table>\n<tr>"
               "<th class=\"l\">factor</th><th>S1</th><th>95%% CI</th>"
               "<th>ST</th><th>95%% CI</th><th>interaction</th></tr>\n");
    for (size_t i = 0; i < r->n_indices; i++) {
        const sobol_index_t *x = &r->indices[i];
        char *nm = doe_html_escape(x->name);
        fprintf(f, "<tr><td class=\"l\">%s</td><td>%.3f</td><td>[%.2f, %.2f]</td>"
                   "<td>%.3f</td><td>[%.2f, %.2f]</td><td>%.3f</td></tr>\n",
                nm ? nm : "", x->s1, x->s1_lo, x->s1_hi, x->st, x->st_lo, x->st_hi, x->st - x->s1);
        doe_free(nm);
    }
    fprintf(f, "</table>\n</body></html>\n");

    fclose(f);
    return 0;
}

int robust_write_tgu(const robust_result_t *r, const char *path, char *err) {
    FILE *f = fopen(path, "w");
    if (!f) { snprintf(err, DOE_ERR_SIZE, "cannot write '%s'", path); return -1; }

    fprintf(f, "# survivors.tgu — generated by robust (Morris -> Sobol survivors)\nfactors:\n");
    const doe_space_t *s = &r->subspace;
    for (size_t i = 0; i < s->factor_count; i++) {
        const doe_factor_t *fac = &s->factors[i];
        if (fac->scale == DOE_CATEGORICAL) {
            fprintf(f, "  %s: ", fac->name);
            for (size_t l = 0; l < fac->level_count; l++) {
                fprintf(f, "%s%s", (l ? ", " : ""), fac->levels[l]);
            }
            fprintf(f, "\n");
        } else {
            double lo = fac->lo, hi = fac->hi;
            double mid = (fac->scale == DOE_LOG) ? sqrt(lo * hi) : 0.5 * (lo + hi);
            fprintf(f, "  %s: %.6g, %.6g, %.6g\n", fac->name, lo, mid, hi);
        }
    }

    fclose(f);
    return 0;
}
